### PR TITLE
Corrected the text equation in the "Aplanatic points" example

### PR DESCRIPTION
**Pull request by StasFainer**

### CODE REVIEW

**Comment by ricktu288** [comment]
I have added the "description" field in data.json, and now it is more appropriate to move the large texts in some of your examples to the descriptions. Note that you can use LaTeX in the description (see "Images from Two Mirror" example), and you can link to other examples using HTML syntax.

Also, I think it may not be appropriate to call the items "examples" in the gallery webpages, as people linking directly to the individual pages are more likely to use the simulations to help them understand optical concepts than to help them know how to use the simulator app.

**Comment by StasFainer** [comment]
About the description field - that's a great addition, although at least in some of the examples I think it would be beneficial to leave some of the original text in the simulation itself (so that the user would see it while checking the simulation - for example a suggestion to press "Extended rays", etc.). In the simulation text I'll leave only what I think is really necessary for the user to see whilst checking the simulation.
I'll gradually update the "description" field in my examples, and will definitely use LaTeX and HTML syntax for the linking!

About the naming of the items - I'll change it to something more accurate and descriptive (very soon).

**Comment by ricktu288** [comment]
Of course I do not mean that all the texts should be moved to the description. Just the long ones which are not referring to any position in the scene or the simulator.

For the items name, I do not mean the names of the items are inaccurate. I mean the term "example" is inaccurate. For instance, in the sentence 'the two foci of the "Hyperbolic mirror" example are also aplanatic points', you refer to the "Hyperbolic mirror" as an example. But the people landing on this page may not take the item as an "example" of the simulator.

In the descriptions of my items I called them "simulations". I cannot find a better term. Maybe "scenes"? But in the future, I may allow one item to have several scenes (to avoid awkward combination of sub-scenes as is happening currently sometimes).

**Comment by StasFainer** [comment]
About the items name, I thought you referred to something else... (the description on the LinkedIn page)
In any case I think it all depends on your interpretation of the term "example" in this context, still, I'll change it to "simulations", just to be sure there isn't any misunderstanding.

**Comment by ricktu288** [comment]
You can also add references (if suitable) using HTML links.

**Pull request merged**
