### PR TITLE
Added three examples

### PR DESCRIPTION
**Pull request by StasFainer**
The examples are:

1. Retroreflectors
2. Maze solution
3. Optical cavity

### CODE REVIEW

**Comment by ricktu288** [comment]
The "maze solution" example is a bit misleading because it is somehow based on coincidence. I think the proper way is to consider a maze with only one exit and no entry, then if the system is ergodic, then no matter where you put the initial ray, it will go to the exit in the end.

**Comment by StasFainer** [comment]
Even when the maze is only with one exit and no entry, certain rays won't exit (for this simulation and this specific maze), for example this one - 
image

However, after what you wrote I thought about this modification - 
The maze can have only one exit and no entry, like you wrote, and then the user(following the appropriate text instruction) could play around with moving a 360 degree dense point source around different places inside the maze, to see the result - 

image

For example in the following example, the ray propagation continues a couple of seconds until some of the rays finally exit the maze - 

image


Do you have something else in mind?

**Comment by ricktu288** [comment]
The reason why certain rays won't exit is that the slope of the ray is a simple rational number. I think for irrational slope (just turn of the grid and randomly drag the ray, it will be good enough), it should always find an exit. Personally, I think a single ray is better than a point source because people can somehow watch it trajectory as it find its way to the exit.

**Comment by StasFainer** [comment]
The thing is that even when I move the ray without the grid randomly, most of the times it doesn't exit the maze.
If what you're saying about the irrationality of the slope is correct, then maybe the reason for this is that even when you change the slope of the ray randomly without the grid, the coordinates of the start and end of the ray are stored in the computer as rational numbers, and so is the actual slope of the ray.

**Comment by ricktu288** [comment]
I mean drag one control point of the ray, rather than moving the entire ray.

**Comment by StasFainer** [comment]
That's what I did.

**Comment by ricktu288** [comment]
Then maybe the point source solution you mention earlier is better.

The reason I become aware of these details that may mislead users is that I am planning to make a gallery page for the examples and hence make the examples google-searchable. And I don't want to mislead the "pedestrian" people who are not very into optics.

**Comment by StasFainer** [comment]
Sure no problem.

**Comment by ricktu288** [comment]
I still think using a single ray is better. At least it solves the maze with quite high probability. I will update the example by myself.

**Pull request merged**
