### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by StasFainer**
Edited description of "Minimum deviation angle" simulation

### CODE REVIEW

**Comment by StasFainer** [comment]
On second thought, maybe it's better that the python scripts will be in your repository.
Whatever you prefer..

**Comment by ricktu288** [comment]
Yes, I think it is better to put the python script in my repo and change the link to an internal download link. I think external links should only be used for reference.

GitHub will still count that python code as your contribution, even if it is not in your repo.

**Comment by StasFainer** [comment]
Sure no problem - feel free to make the necessary changes.

**Comment by ricktu288** [comment]
I will do that maybe next week.

**Comment by ricktu288** [comment]
I think the title "Spherical resonator" is not appropriate because you used ideal curved mirrors rather than spherical mirrors.

Also note that the Gallery will support multilingual in the future, and it is currently being translated to other languages. This means that old items should not be updated again and again that often in the future. Otherwise, I cannot find a good way to keep everything synchronized.

**Comment by StasFainer** [comment]
About the translations - I understand, it really is a problem. I'll keep that in mind from now on.

About the title, ideal and spherical mirrors coincide only in the paraxial approximation, and I used the term "Spherical" because it implies a geometry with two mirrors.
Maybe something like "Two-mirror optical cavity" is better, since the original title ("Optical cavity") is not informative enough - there are different types of geometries for an optical cavity - ring cavity, bow-tie cavity, etc.

**Pull request merged**
