### PR TITLE
Rotate/translate sliders for line segments

### PR DESCRIPTION
**Pull request by tlambert03**
hey @ricktu288 and thanks for this great tool.  I'm opening a PR rather than a discussion just to provide some concrete examples, but i expect this to require discussion.

One thing I often want to do when teaching is to show how the system changes when one component gets translated/rotated.  This is of course possible with clicking and dragging, but I wasn't able to find a way to move both points of a line segment in a restricted way, for example, to rotate a mirror around the midpoint, or to translate a lens along it's normal vector/optical axis.   There are often too many unconstrained degrees of freedom, I wanted to do something like this:

https://github.com/user-attachments/assets/22c7e6ce-53ef-4a3a-8ffd-782802f06b5e

or this:

https://github.com/user-attachments/assets/c5bb66fd-04e0-4192-819e-5342016b8865

This PR is an example that adds sliders to the `LineObjMixin` ... but I'd be more than happy to move that functionality elswhere if you generally like the concept, but don't like the UI.  For example, I can imagine adding a "rotate" handle, or some sort of normal-vector handle that strictly translates a component along its normal

Or, if what I'm trying to do is already possible in a different way, feel free to let me know :)

### CODE REVIEW

**Comment by ricktu288** [comment]
See the "Constrained dragging" and "Group, rotate, and scale objects" sections in the Help button at the lower right corner of the simulator.

Custom sliders can also be achieved using the "Module" feature. See Tools -> Other -> Import modules -> Make custom modules.

If you think sliders to move or rotate all types of objects is beneficial, then it should be implemented for all types of objects and not just for linear-shaped objects. Possibly an approach is to add an abstract `rotate` method in `SceneObj` method in addition to `move` and create a specialized UI rather than squeezing sliders along with the non-geometrical options.

**Comment by tlambert03** [comment]
thanks, yeah I thought there must be something like this :)

I'm not yet convinced rotation sliders are beneficial for all objects... still trying to grasp the current recommended approach. is it this?

https://github.com/user-attachments/assets/a6251776-2187-4233-826b-9e25dd338108

that does feel *slightly* clunky (at least 4 clicks) to do a simple rotate around midpoint... and i definitely had to read the instructions and try a few times to get it right.  But it's great to know that the functionality is there.  sorry I missed it.  I'll close this PR, since its purpose has been served.  If I think of any improvements on the current behavior, I'll open a new issue.  thanks

**Comment by tlambert03** [comment]
for constrained dragging, there's no "drag along the normal" right?  just drag along the grid?

**Comment by ricktu288** [comment]
The constrained dragging works for the normal direction, even if it is not explicitly documented.

**Comment by ricktu288** [comment]
In the case shown in your previous video, simply holding Ctrl and drag an endpoint of the mirror works (even if the length of the mirror will not be fixed), and don't need to create a handle.

**Comment by tlambert03** [comment]
right, but then you're just moving a single point, and not rotating around the midpoint, correct?

**Pull request closed without merging**
