### PR TITLE
Added examples - "Camera obscura" and "Interrogation room"

### PR DESCRIPTION
**Pull request by StasFainer**

### CODE REVIEW

**Comment by ricktu288** [comment]
Dan you explain more about the "interrogation room" example? The dark room is not really dark actually. It appears to be dark due to the truncation error of the canvas renderer at the extremely high ray density you set.

**Comment by StasFainer** [comment]
The point of the "interrogation room" example is to demonstrate that the suspect can only see the reflection of the room where he is present (when pressing the "All Images" option, a reflection of the lamp appears inside the "Dark room", and it's this reflection that he sees).

The "Dark room" is dark in the sense that there isn't any light emitted from the "Dark room" to the suspect room (it is a dark room relative to the suspect) - 
No light is generated inside the "Dark room" and the "Dark room" absorbs the light from the suspect room. Therefore the suspect can't see anything inside the "Dark room".

Obviously this is an **ideal** scenario, and in reality the "Dark room" may emit light (via generation/reflection), but when this effects are minimized accordingly, this is a real practical example.

Honestly I didn't understand the part about the truncation error, and I set the high ray density only to make the lamp look more realistic.

**Comment by ricktu288** [comment]
I mean, the background of the dark room looks completely black, which may give the user a false impression that the beam splitter somehow blocks all the light from the lamp. But in fact the transmission ratio of the beam splitter is 50%.

**Comment by StasFainer** [comment]
Now the dark room looks likes this - 
image


I can set the brightness of the lamp to 1, which will make the background of the dark room appear brighter, like this - 
image


Is this better?

**Comment by ricktu288** [comment]
ok

**Pull request merged**
