### PR TITLE
Add Diffraction Grating

### PR DESCRIPTION
**Pull request by gljames24**
I put it in blockers as it is essentially a bunch of aperatures, but I can change it if you want. Other seems like it's non-optical. I also made a monochromometer example to go with it. Let me know if there are any issues.
[Monnochromometer.json](https://github.com/ricktu288/ray-optics/files/14737019/Monnochromometer.json)

Screenshot from 2024-03-24 16-26-43
Oh, I hadn't updated the tooltip image. I'm currently using the apeture on as a placeholder for something like this:
Screenshot from 2024-03-24 16-32-51

### CODE REVIEW

**Comment by ricktu288** [comment]
1. Are the angles correct? It seems that the angles are equally spaced but they shouldn't be.
2. The central line of the reflection grating appears to be like a retroreflector, but it should be like a mirror.
Formula for gratings
3. Do the intensities make sense? In particular, why the total outgoing intensity sometimes exceed that of the incident ray?

**Comment by ricktu288** [comment]
Maybe just approximate

**Comment by gljames24** [comment]
I realized messing around with a diffraction grating that the angle seems to change the apparent density. I think you have effectively have more lines per mm with higher and lower incident angles as the diffraction grating essentially looks like the short side of a triangle with the actual grating as the hypotenuse, but it also seems to make the angle increase more so on the side further away from the incident ray, so I don't know how the coherence is changing with the angle and will have to look more into it. I think it might be impacted by the geometry of the lines on the physical grating as well.

Currently, I have fixed it so that the m values have their own correct values and moved the pairs of rays into the same for loop to prevent having to recalculate the value. I found a good equation for the intensity, but it'll take me a bit to add it.

**Comment by gljames24** [comment]
https://i.imgur.com/qG2YO7A.mp4

**Comment by ricktu288** [comment]
My previous comment already contains the formulas for the output angles for a general incident angles.

The intensity is a more difficult problem. I think the the actual intensities of the output rays depends on the detail structure of the grating and also on the polarization.

However, since you put the tool under "blocker", I think maybe one solution is to use the simplest model of an array of linear blockers. But then we also need another parameter for the width of each slit (or the ratio of the width to the separation of lines). I don't have the formula but I think it can be derived from the phaser formalism introduced in most general physics textbook.

**Comment by ricktu288** [comment]
Or maybe just ignore the output intensity profile for now and make it maybe uniform.

It looks like realistic grating usually have very complicated profiles. I searched for a while and found this

https://www.researchgate.net/figure/Normalized-transmitted-intensity-distribution-for-a-blazed-and-b-symmetric-Si_fig4_231003007

**Pull request merged**
